M48
; DRILL file {KiCad (6.0.6)} date Sat Aug  6 18:53:42 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-06T18:53:42-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X2.1045Y-1.5744
X2.2955Y-1.5744
T2
X2.0927Y-1.4551
X2.3073Y-1.4551
T0
M30
